version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    volumes:
      - ./postgres_data/:/var/lib/postgresql/sql_data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - my_network

  web:
    build: .
    depends_on:
      - 'postgres'
    command: bash -c "sleep 20 && python app/02_movies_admin/manage.py migrate && python app/02_movies_admin/manage.py createsuperuser --noinput && python app/02_movies_admin/manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}"
    volumes:
      - ./:/usr/src/empty_project/
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env_file:
      - ./.env
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
