version: '3'

services:
  web_server:
    build: .
    depends_on:
      - 'postgres'
    volumes:
      - ./:/usr/src/empty_project/
    expose:
      - ${DJANGO_PORT}
    command: gunicorn movies.wsgi:application --bind ${DJANGO_HOST}:${DJANGO_PORT}
    env_file:
      - ./.env.web_server
    networks:
      - my_network

  postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    volumes:
      - ./postgres_data/:/var/lib/postgresql/sql_data/
    env_file:
      - ./.env.db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
