version: '3'
services:
  server:
    build: ./app
    depends_on:
      - 'postgres'
    volumes:
      - ./:/usr/src/
    expose:
      - ${DJANGO_PORT}
    command: gunicorn movies.wsgi:application --bind ${DJANGO_HOST}:${DJANGO_PORT}
    env_file:
      - ./env_variables/server.env
    networks:
      - movies_network

  postgres:
    build:
      context: ./app
      dockerfile: ./postgres.Dockerfile
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    env_file:
      - ./env_variables/db.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - movies_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service
    ports:
      - "80:80"
    networks:
      - movies_network

networks:
  movies_network:

volumes:
  postgres_data:
